basePath: /api/v1
definitions:
  entity.ExpectedProfit:
    properties:
      feed:
        $ref: '#/definitions/entity.Feed'
      investment:
        $ref: '#/definitions/entity.InitialInvestment'
      profit:
        type: number
      sale:
        $ref: '#/definitions/entity.Sale'
    type: object
  entity.Feed:
    properties:
      expectedGmd:
        example: 1.2
        type: number
      percentageAliveWeight:
        example: 2.5
        type: number
      priceKg:
        example: 5.5
        type: number
      regime:
        $ref: '#/definitions/enums.FeedRegime'
    type: object
  entity.Herd:
    properties:
      numberOfAnimals:
        example: 50
        type: integer
      priceKg:
        example: 15
        type: number
      totalWeight:
        example: 2000.5
        type: number
      weightCalculationType:
        allOf:
        - $ref: '#/definitions/enums.WeightCalculationType'
        description: 0=Média, 1=Total
        enum:
        - 0
        - 1
        example: 0
    type: object
  entity.InitialInvestment:
    properties:
      avgWeight:
        format: float64
        type: number
      perHead:
        format: float64
        type: number
      totalValue:
        format: float64
        type: number
    type: object
  entity.ProfitRequest:
    properties:
      days:
        example: 30
        type: integer
      feed:
        $ref: '#/definitions/entity.Feed'
      herd:
        $ref: '#/definitions/entity.Herd'
      sale:
        $ref: '#/definitions/entity.Sale'
    type: object
  entity.Sale:
    properties:
      calculationType:
        allOf:
        - $ref: '#/definitions/enums.WeightCalculationType'
        description: 0=Média, 1=Total
        enum:
        - 0
        - 1
        example: 0
      expectedDate:
        example: "2025-09-20T00:00:00Z"
        type: string
      finalAvgWeight:
        example: 350
        type: number
      priceKg:
        example: 20
        type: number
    type: object
  enums.FeedRegime:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - FeedRegimeOpen
    - FeedRegimeConfinedSemi
  enums.WeightCalculationType:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - WeightCalculationAverage
    - WeightCalculationTotal
info:
  contact: {}
  description: API para cálculo de lucro esperado
  title: Profit API
  version: "1.0"
paths:
  /profit/calculate:
    post:
      consumes:
      - application/json
      description: Recebe dados de rebanho, ração e venda e retorna o lucro esperado
      parameters:
      - description: Dados de entrada
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entity.ProfitRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.ExpectedProfit'
      summary: Calcula o lucro esperado
      tags:
      - Profit
swagger: "2.0"
